### ISSUE TITLE
Why is alloc used instead of malloc?

### ISSUE THREAD

**Issue by awnumar** [stouset/go.secrets#1]
Over [here](https://github.com/stouset/go.secrets/blob/master/secrets.go#L113), you have the following code:

```
if err = sec.secret.alloc(C.size_t(len)); err != nil {
		return nil, err
}
```

As far as I know, `alloc` is a pretty non-standard function, similar to `malloc`. Why did you choose to use it here?

**Comment by stouset** [comment]
This is not libc alloc, it is a function implemented in this library.

**Comment by awnumar** [comment]
Ah, cheers.
